---
type: event
url: http://192.168.100.107:8080/eca-test-event/webapi/myresource/true
name: "test  event"
---
type: condition
url: http://192.168.100.107:8080/eca-test-event/webapi/myresource/true
name: "test condition"
---
type: action
url: "http://192.168.100.107:8080/eca-test-event/webapi/myresource/fired"
name: "test   Action"